# Generated by Django 5.0.6 on 2024-05-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('age', models.IntegerField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('address_street_1', models.CharField()),
                ('address_street_2', models.CharField(blank=True)),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
